apiVersion: v1
kind: PersistentVolume
metadata:
  name: cluster-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0cc43b2b454df0a24
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-192-168-1-151.eu-west-2.compute.internal # The node to be scheduled to.
          