apiVersion: v1
kind: Pod
metadata:
  name: nginx2
spec:
  affinity:
    podAffinity: # Enforces that the Pod should be scheduled on a node based on this label attached to Pods already running on that node
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions: # matches a label assigned to a pod
          - key: region
            operator: In
            values:
            - eu-west-2
        topologyKey: topology.kubernetes.io/region # matches a label assigned to a node
  containers:
  - name: nginx-container-2
    image: nginx:latest
