apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default: # this section defines default limits
      cpu: "0.5"
    defaultRequest: # this section defines default requests
      cpu: "0.5"
    max: # max and min define the limit range
      cpu: "1"
    min:
      cpu: "0.1"
    type: Container
