apiVersion: v1
kind: Pod
metadata:
  labels:
    region: eu-west-2
  name: nginx1
spec:
  containers:
    - image: nginx:alpine
      name: nginx-container-1
  nodeSelector:
    topology.kubernetes.io/region: eu-west-2
