kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
          command: [ "sh", "-c", "sleep 1h" ]
      securityContext:
        runAsUser: 1000 # root user
        runAsGroup: 3000