kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myapp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 8Gi
  volumeName: cluster-pv
