apiVersion: v1
kind: Pod
metadata:
  name: nginx-manual
spec:
  containers:
  - image: nginx:alpine
    name: nginx
  tolerations:
    - key: key1
      operator: Equal
      value: value1
      effect: NoSchedule
