apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota-1
  namespace: dev-1
spec:
  hard:
   pods: "1"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota-2
  namespace: dev-2
spec:
  hard:
   pods: "1"
