apiVersion: v1
kind: Pod
metadata:
  name: nginx3
spec:
  affinity:
    podAntiAffinity: # Expresses a preference against scheduling the Pod on nodes with this label atached to Pods already running on that node
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions: # matches a label assigned to a pod
          - key: region
            operator: In
            values:
            - eu-west-2
        topologyKey: topology.kubernetes.io/region # matches a label assigned to a node
  containers:
  - name: nginx-container
    image: nginx:latest
