apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: nginx:alpine
      # Execute the bellow command & argument in the terminal
      command: ["/bin/sh"]
      args: ["-c", "echo The database password is $(echo $DB_PASSWORD)"]
      # Add config map via environmental variables
      env:
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: DB_PASSWORD
