kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubectl-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubectl
  template:
    metadata:
      labels:
        app: kubectl
    spec:
      containers:
        - name: kubectl
          image: bitnami/kubectl
          ports:
            - containerPort: 80
          command: ["/bin/bash"]
          args: ["-c", "while true; do sleep 3600; done"]
      #serviceAccountName: svc-acct