apiVersion: v1
kind: Pod
metadata:
  labels:
    name: nginx
  name: nginx
spec:
  containers:
  - image: nginx:alpine
    name: nginx
    ports:
      - containerPort: 80
    resources:
      requests:
        cpu: "0.1"
        memory: "128M"
      limits:
        cpu: "0.1"
        memory: "128M"