apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  # this deployment has this label tag
  labels:
   name: nginx-deployment
spec:
  selector:
  # match pod schemas having this label tag
    matchLabels:
      name: nginx
  # create 3 replicas
  replicas: 3
  # the template of the pod
  template:
    metadata:
      name: nginx-pod
      # this pod has this label tag
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25.3
          ports:
            - containerPort: 80
          # resource limit
          resources:
            requests:
              cpu: "0.1"
              memory: "128M"
            limits:
              cpu: "0.1"
              memory: "128M"
  # deployment strategy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%